version: '3.8'

services:
  db1:
    build: ./mic-dbservice
    container_name: db1
    environment:
      - DB_PORT=4000
      - PEERS=http://db2:4000,http://db3:4000
    ports:
      - "4001:4000"
    networks:
      - app-net

  db2:
    build: ./mic-dbservice
    container_name: db2
    environment:
      - DB_PORT=4000
      - PEERS=http://db1:4000,http://db3:4000
    ports:
      - "4002:4000"
    networks:
      - app-net

  db3:
    build: ./mic-dbservice
    container_name: db3
    environment:
      - DB_PORT=4000
      - PEERS=http://db1:4000,http://db2:4000
    ports:
      - "4003:4000"
    networks:
      - app-net

  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db1
      - db2
      - db3
    networks:
      - app-net

  api-service:
    build: ./mic-apiservice
    container_name: api-service
    environment:
      - API_PORT=3000
      - DB_SERVICE_URL=http://load-balancer:4000
    ports:
      - "3000:3000"
    depends_on:
      - load-balancer
    networks:
      - app-net

networks:
  app-net:
